AllCops:
  NewCops: disable

Layout/EndOfLine:
  EnforcedStyle: lf

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Naming/VariableNumber:
  Enabled: false