require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/Files", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # File. As you add validations to File, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FileNode.create! valid_attributes
      get file_nodes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      file_node = FileNode.create! valid_attributes
      get file_node_url(file_node)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_file_node_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      file_node = FileNode.create! valid_attributes
      get edit_file_node_url(file_node)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new File" do
        expect {
          post file_nodes_url, params: { file_node: valid_attributes }
        }.to change(FileNode, :count).by(1)
      end

      it "redirects to the created file" do
        post file_nodes_url, params: { file_node: valid_attributes }
        expect(response).to redirect_to(file_node_url(FileNode.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new File" do
        expect {
          post file_nodes_url, params: { file_node: invalid_attributes }
        }.to change(FileNode, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post file_nodes_url, params: { file_node: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested file" do
        file_node = FileNode.create! valid_attributes
        patch file_node_url(file_node), params: { file_node: new_attributes }
        file_node.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the file" do
        file_node = FileNode.create! valid_attributes
        patch file_node_url(file_node), params: { file_node: new_attributes }
        file_node.reload
        expect(response).to redirect_to(file_node_url(file_node))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        file_node = FileNode.create! valid_attributes
        patch file_node_url(file_node), params: { file_node: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested file" do
      file_node = FileNode.create! valid_attributes
      expect {
        delete file_node_url(file_node)
      }.to change(FileNode, :count).by(-1)
    end

    it "redirects to the Files list" do
      file_node = FileNode.create! valid_attributes
      delete file_node_url(file_node)
      expect(response).to redirect_to(file_nodes_url)
    end
  end
end
